### ISSUE TITLE
Start filling out the missions in section 1

### ISSUE THREAD

**Issue by andreimoment** [andreimoment/tangomanual#1]
@mitramartin,

please start filling out the missions in v1. I've created all of them as sample pages so that you can just replace the existing content.

Let me know if you have any questions.

Make sure to replace the youtube id in the data section of the page (very top) with the actual youtube video embed id.

Here's the mission list:
https://github.com/andreimoment/tangomanual/tree/master/v1

Click on a filename to view and then on the pencil icon to edit it.

Here's the index page: 
https://github.com/andreimoment/tangomanual/blob/master/v1/README.md

Discuss general editing questions here.

**Comment by andreimoment** [comment]
@mitramartin please see this issue

**Comment by mitramartin** [comment]
can you show me how this works tomorrow sunday maybe?

-- 
Mitra Martin
310-854-2466
www.mitramartin.com
www.oxygentango.com

**Comment by mitramartin** [comment]
Sure! Can we do it around noon? I think I'll go to the mar vista market
around 10:30 am and then we can meet at home. It'll take 15 minutes.

**Comment by mitramartin** [comment]
i have a meeting at noon. but i could do 1:30. your place?

-- 
Mitra Martin
310-854-2466
www.mitramartin.com
www.oxygentango.com

**Comment by mitramartin** [comment]
1:30pm works. 

Andrei Andreev

**Comment by andreimoment** [comment]
Here's a link to the mirror game (1-a.md)

https://github.com/andreimoment/tangomanual/blob/master/v1/1-a.md

Click on the pencil to edit it (must be signed into github)

**Comment by mitramartin** [comment]
thanks - yes but how do i see the actual link like a student would see it ?


--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>

**Comment by andreimoment** [comment]
View published page:
https://andreimoment.github.io/tangomanual/v1/1-a

Edit the page content:
https://github.com/andreimoment/tangomanual/blob/master/v1/1-a.md

**Comment by mitramartin** [comment]
mersi

--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>
