### ISSUE TITLE
more videos on each mission page? 

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#18]
@andreimoment  it would be cool if we could have multiple videos on a mission page

**Comment by andreimoment** [comment]
What would that look like? Would videos just appear after each other without any explanation? Would they require a title above each video? If there's a title, would it ever contain a summary?

Replacing one the one video setup with a list-of-videos setup is simple. Adding multiple videos intermixed with text could be challenging... Github does not allow embedding of videos directly, we are using special code to work around that.

**Comment by andreimoment** [comment]
Added multi-video functionality. Multiple videos will be listed above each other.

List the videos like this:

~~~
---
...
youtube: 
    - "v_aLOHMilBE"
    - "v_aLOHMilBE"
    - "v_aLOHMilBE"
...
---
~~~

See [4-f-multi](https://github.com/andreimoment/tangomanual/blob/master/v1/4-g-multi.md) for details. The page is visible at http://tangomanual.com/v1/4-f-multi

**Comment by andreimoment** [comment]
Apologies, the sample page is 4-g-multi, not 4-f-multi

**Comment by andreimoment** [comment]
I think it would be useful to be able to clarify why a mission has more than one video. Maybe we can do this above the list of videos (as we won't have clarification text for each individual video)

**Comment by andreimoment** [comment]
Or maybe we could use the YouTube video titles for that. I think this would be the simplest and also very clear approach.

**Comment by andreimoment** [comment]
@mitramartin let me know if this set up works for you so I can close the issue.

**Comment by mitramartin** [comment]
@andreimoment this works great. i think we can use the youtube video titles for that. this is just in case someone else wants to share/include a video that shows the mission from a different angle, or in some cases where the mission has different parts that could be better shown in separate videos. thank you for this solution! :)
