### ISSUE TITLE
Create a lulu link and description of the printed manual

### ISSUE THREAD

**Issue by andreimoment** [andreimoment/tangomanual#27]
@mitramartin take a look and possibly improve the copy for the printed version:

https://github.com/andreimoment/tangomanual/blob/master/_includes/tm__buy_manual.html

It appears on the index page http://tangomanual.com/v1/index.html

**Comment by mitramartin** [comment]
@andreimoment i think it would be to include the amazon link when it is live since more people use amazon

**Comment by mitramartin** [comment]
@andreimoment i edited the text :)

**Comment by andreimoment** [comment]
I couldn't generate an isbn because Amazon doesn't seem to allow it for
this spiral bound format. I'll investigate more but for now maybe we can
use lulu direct sales

**Comment by andreimoment** [comment]
Lulu supports only certain formats for (Free!!) Lulu-issued ISBN and Amazon distribution: 
http://connect.lulu.com/t5/ISBN-Distribution/Which-Products-are-Eligible-for-Retail-Distribution/ta-p/33150

Option for 3rd party ISBN: https://www.myidentifiers.com/get-your-isbn-now ($300 for 10 ISBNs... what?! ) Still not sure if Lulu would distribute spiral-bound to Amazon even if we were to get a 3rd party ISBN.

**Comment by andreimoment** [comment]
More ISBN-related info:

* an overview of ISBN services and reasons for using one or the other: (the gist is that cheap ISBNs are purchased in bulk by publishing companies and the books get associated with these companies as the publisher) https://www.thebookdesigner.com/2010/11/isbn-101-for-self-publishers/
* A Lulu service to purchase an ISBN and associate it with the author's company. Saves about $20. http://www.lulu.com/shop/yourisbn/service/product-yourisbn.html

**Comment by mitramartin** [comment]
let's just keep it on lulu for now? until we see lots of demand...

**Comment by andreimoment** [comment]
I saw you edited the link, like the new copy.

I am thinking that we may want to add a dedicated webpage containing a page spread from the printed manual with callouts illustrating the different sections, like a technical illustration.

**Comment by mitramartin** [comment]
okay. i will work on promo copy and illustrations for that dedicated page

**Comment by mitramartin** [comment]
andrei, could you add the current text to the bottom of the home page too? @andreimoment

**Comment by andreimoment** [comment]
Manual purchase link is available. Closing.
