### ISSUE TITLE
2-F soft boleo video doesn't show a boleo 

### ISSUE THREAD

**Issue by andreimoment** [andreimoment/tangomanual#3]
@mitramartin, the video does not correspond to the mission. 

The reason may be that there are one or two duplicate videos so it may be a good idea to watch each video before renaming and embedding.

**Comment by andreimoment** [comment]
Mitra, did you fix this? If yes, please reply here and close the issue.

**Comment by dorkydi** [comment]
The page for 2-G seems to show the video for 2-F (soft boleo), while the page for 2-F seems to show the video for 2-E (the other system).

**Comment by mitramartin** [comment]
i think i put in the correct video (video title should say 2-f corrected, this one https://www.youtube.com/watch?v=dEwloNSOm88
but, it is not currently appearing yet

**Comment by mitramartin** [comment]
fixed
