### ISSUE TITLE
should we add glossary etc to webpage? 

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#34]
...or should that only be in the manual?

**Comment by mitramartin** [comment]
@andreimoment my thought is that the glossary and all the other appendix material can be extra bonus accessed by buying the workbook

**Comment by andreimoment** [comment]
Maybe we can try it this way and get feedback. My vision is for all information to be available online eventually.

**Comment by mitramartin** [comment]
ok sounds good
