### ISSUE TITLE
mission re-naming protocol and notes

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#36]
stefan suggests that they have more distinct names. e.g., 6-c could be "The First Full Turn"

**Comment by andreimoment** [comment]
Easy to change in the online version, but getting out of sync with the
printed version. We need a protocol for that.

**Comment by mitramartin** [comment]
yes. okay. we should also rename 4-e Caminar and 4-c Apilado so they are more descriptive.

**Comment by andreimoment** [comment]
Maybe we can rename 4-E to

**4-E Caminar: More Descriptive Name Here**

and thus maintain sync with the printed manual?

**Comment by mitramartin** [comment]
how about this 
Code: "New Tame [Old Name]"

I changed 4-E and 4-C in this way, take a peek

will it appear this way in the new way on the table of contents / mission list?

**Comment by mitramartin** [comment]
nvm i updated the missions list

**Comment by andreimoment** [comment]
Could we use regular parentheses instead of square brackets when renaming?

**Comment by andreimoment** [comment]
Changed the square brackets to parentheses -- please use regular parentheses when you want to, well, put things in parentheses.
