### ISSUE TITLE
Anatomy of a Mission

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#39]
@andreimoment we need a page on this: 

Anatomy of a mission!

Lots of missions teach new movement material. Here is how they work: 

START:
GREETING: Howdy! Connect humanly. Eye contact, name, howzit going
BUILDS ON: Warm up, lead something they already know that's somehow similar.

PART A: FOLLOWING 
> FOLLOW SOLO WALKTHROUGH: Show them the structure of the follower's part, help them walk through it slowly, solo
> FOLLOW ROUGH DRAFT: They follow you as you lead it in, slowly, using a practice hold
> ADD EMBRACE: They follow you in whatever is closest to the "real" embrace(s) you'd use  
> IMPROVISED FOLLOWING: Lead them in half a song or so and interleave the new element with a few other things that have similar entrances

PART B: LEADING
> LEAD STUMBLETHROUGH: You help them lead it in practice hold super slowly. That means, partly backleading them and partly telling them what to do. "Switch, so now you're on your right foot. Other foot. Okay good. Now take a step forward."
> SPECIAL LEADER STUFF: Show them any new, weird things that could help them leading, and help them do those things solo
> LEADER DRESS REHEARSAL: Have them lead it a few times in practice hold, smoothing it out. 
> LEAD WITH EMBRACE: Have them lead in whatever is closest to the "real" embrace(s) 
> REMOTE CONTROL LEAD: Have them lead half a song and tell them what element to do when E.g. "Okay, lead me to the cross. Next do an ocho cortado. Now, rock step open. Now..." 
> IMPROVISED LEADING: Give them a few other things to lead that fit with the new thing and have them lead a song using just those elements

PART C: MUSICALITY
> TAP KEY RHYTHM ON THEIR BODY
> HAVE THEM TAP IT ON YOUR BODY
> HAVE THEM WALK THROUGH IT IN THE NEW RHYTHM
> DO IT TOGETHER IN NEW RHYTHM

PART D: EXPANSION PACK! 
> OTHER SIDE: Handward instead of hugward, light side instead of dark
> OTHER SYSTEM: Crossed instead parallel or vice versa
> OTHER ROLE: Lead the follower to do the leader's part (leader does what follower did) 
> OTHER CROSS: Change all forward crosses to backward crosses and vice versa
> STRETCH OR CURL: If it curls, stretch it out. If it's straight, make it curl
> CHANGE RHYTHM

CLOSING: 
> GRATITUDE: Be sure to thank each other, and if you want to work more find out when you'll see each other next at practica. 
> IMPROVE THE SYSTEM: Make notes in your manual, and send suggestions to the mission writers.

**Comment by andreimoment** [comment]
@mitramartin  I added anatomy of a mission:

View:
http://tangomanual.com/v1/anatomy-of-a-mission

Edit:
https://github.com/andreimoment/tangomanual/blob/master/v1/anatomy-of-a-mission.md

1. Will it be a part of the appendix? If so, ideally it would match the printed manual appendix. Which would mean adding the rest.
2. I suggest removing the "Part X" sections of the headlines. So, "Part A: Following" would become "Following"

**Comment by mitramartin** [comment]
great. done!

**Comment by andreimoment** [comment]
Not sure what you think on 1. and 2.? Should we add the rest of the appendix, to match the manual?

**Comment by mitramartin** [comment]
yes we can add the rest of the manual's appendix

yes i agree we can remove the Part X

--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>
