### ISSUE TITLE
how do we find/invite/add/tag new project collaborators?

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#40]
i saw her comment on something, but now i cannot see her when i write @

**Comment by andreimoment** [comment]
I wasn't able to find anything by her... what is her github username?

**Comment by andreimoment** [comment]
I believe you can tag someone *after* they've made a contribution to a project (submitted or replied to an issue, or submitted a pull request). I can't find any contributions by Dianne.

**Comment by mitramartin** [comment]
she commented on the soft boleo issue that is closed: https://github.com/dorkydi

**Comment by andreimoment** [comment]
I can see that it's possible to use @name for her on that issue. Maybe she needs to create at least one pull request so that you can include her on new issues which she has not participated on, like it is possible with @andreinla, the account I used to test the pull request process.

I'll check with github to see if there's a way around this.

**Comment by andreimoment** [comment]
@dorkyd, did you get a notification for this message?

**Comment by andreimoment** [comment]
@dorkydi, did you get a notification for this message? Mitra and I are trying to figure the details of how github name mentions work.

**Comment by dorkydi** [comment]
Yes!

- Diane Yoon

**Comment by andreimoment** [comment]
Well that's settled then. Mitra, you can @mention any github username in any comment and that person will be notified.

Nice username, @dorkydi 😎

**Comment by mitramartin** [comment]
thanks!

**Comment by mitramartin** [comment]
okay, just to practice, i'm trying to tag diane on issue "Revising mission template: important! #38" but i cannot seem to do that. do we need to "invite" her to be a "collaborator" on this "repository"?  

sorry to be a github noob everyone! @dorkydi @andreimoment

**Comment by mitramartin** [comment]
i am also trying to "Add" Thomas and Korey as collaborators. how do i do that?

**Comment by andreimoment** [comment]
@mention her name in a comment on the issue. 

Like you did in this issue (both Dianne and I got notified)

Same goes for Thomas and Korey, what are their github usernames?

**Comment by andreimoment** [comment]
And by name I mean the github username. @mention means calling them like this: @mitramartin

**Comment by mitramartin** [comment]
yes, but it didn't work when i tried to do it from another issue

--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>

**Comment by andreinla** [comment]
You need to type it out the first time. It will not give you a menu as
you're typing unless certain conditions are met (like, this person was
already mentioned in this issue, or has an accepted pull request on the
project or is one of the project owners)

So the menu won't appear ("won't work") but the @mention will notify the
other person ("will work").

**Comment by andreimoment** [comment]
I think I just saw a successful mention of Dianne on the mission topic
structure issue. If that worked, let's close this convo.

**Comment by andreimoment** [comment]
@mitramartin here's the github page on mentions: 

https://github.com/blog/821-mention-somebody-they-re-notified

**Comment by andreimoment** [comment]
Closing this now  we now: @mentions work with any github account.

https://github.com/blog/821-mention-somebody-they-re-notified
