### ISSUE TITLE
ethical standards draft

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#41]
some initial thoughts about articulating professional ethics, along with protocols for crediting, as part of this project: 

https://docs.google.com/document/d/1buPIgTQefSt3_OfFjyPrZ3NthhqVeiTYN6kDrUuaxuU/edit

**Comment by andreimoment** [comment]
Haven't seeing MN it yet but it's a great idea and here's how some huge projects are handling it:

https://github.com/rails/rails/blob/master/CODE_OF_CONDUCT.md

**Comment by mitramartin** [comment]
thx. okay, feeling good about what i put on the homepage as a start.
