### ISSUE TITLE
resources tango safe-houses

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#46]

**Comment by andreimoment** [comment]
My understanding of the term "safe-house" is "a location where a trusted adult or family or charity organization provides a haven for victims of domestic abuse (see also: men and/or women's shelter or refuge)"

I like the term "tango safe house" and at the same time would like to be respectful to anyone who has had to use a non-tango safe house. I have a friend who works with families in domestic abuse situations and I imagine she'd find using the term to denote something celebratory questionable at best.

https://en.wikipedia.org/wiki/Safe_house

**Comment by mitramartin** [comment]
yes. got it. changed in issue #45 too
