### ISSUE TITLE
Create a Patreon campaign and link it in the manual

### ISSUE THREAD

**Issue by andreimoment** [andreimoment/tangomanual#5]
@mitramartin let's talk about creating a Patreon campaign and linking it in the manual.

**Comment by mitramartin** [comment]
okay let's talk about it!

--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>

**Comment by andreimoment** [comment]
Here are the instructions. 

https://patreon.zendesk.com/hc/en-us/articles/203913859--How-do-I-become-a-creator-and-make-a-page-on-Patreon-

I'll create a patreon.md doc where we can iterate on the patreon pitch.

**Comment by mitramartin** [comment]
okay i set up a page but i need to work on the copy: https://www.patreon.com/mitramartin

**Comment by mitramartin** [comment]
https://patreon.com/preview/8d86cba3a3f74752a7a9c31793c8d533

**Comment by andreimoment** [comment]
Love the copy. At first fast read: consider expanding adv-int

Also may end we can reuse some of this copy in the home page (/index.md)

**Comment by mitramartin** [comment]
ok. i'm happy with how it is for now. made some small edits. :)

**Comment by mitramartin** [comment]
hi @andreimoment, did we ever have a page or copy about the patreon? thinking about bringing that back.
