### ISSUE TITLE
global pronouns question

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#51]
I have defaulted to masculine pronouns when referencing leader, feminine pronouns when referencing follower.

my assumption is always that both men and women will learn both roles. 

i would like for the manual's convention with pronouns to be easy, clear, and also make everyone feel comfortable and included. 

thoughts welcome.

**Comment by andreimoment** [comment]
my thoughts: makes it clearer so I welcome it. It is a sensitive matter so it may be useful to clarify the reasoning -- possibly:

"We would like for the manual's convention with pronouns to be easy, clear, and also make everyone feel comfortable and included.

For the sake of ease and clarity, we have defaulted to masculine pronouns when referencing leader, and feminine pronouns when referencing follower. Our assumption is always that both men and women will learn both roles."

**Comment by mitramartin** [comment]
i added this to http://tangomanual.com/v1/ for now

**Comment by andreimoment** [comment]
What do you think? http://tangomanual.com/v1/

**Comment by mitramartin** [comment]
great

**Comment by andreimoment** [comment]
I'll have Julianne take a look, too

**Comment by andreimoment** [comment]
Julianne-approved. Closing. 

Super proud of this language.
