### ISSUE TITLE
beta test language? 

### ISSUE THREAD

**Issue by mitramartin** [andreimoment/tangomanual#53]
i would like to make it prominently clear that this is a test and in development and that we are actively seeking feedback and evolving all the time. should we write BETA TEST on both index pages? @andreimoment

**Comment by andreimoment** [comment]
I think it's a good idea to communicate that the manual is in active development. Maybe we can use this language:

The Tango Manual is under active development which means frequent additions and improvements. You are our community and we invite you to take part in both. To suggest an improvement, consult the [instructions on GitHub](https://github.com/andreimoment/tangomanual#how-to-contribute) or go directly to the [project issues](https://github.com/andreimoment/tangomanual/issues).

**Comment by mitramartin** [comment]
great, added

--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>

**Comment by andreimoment** [comment]
The beta language has been added.
