### ISSUE TITLE
Missions TOC page

### ISSUE THREAD

**Issue by andreimoment** [andreimoment/tangomanual#54]
@mitramartin, after adding the two new paragraphs to the mission index, the index is no longer in sight without scrolling. 

I'd like to consider the main function of this page which is to quickly find a mission from the index. As it is now, it presents content which is not aiding that purpose, first. 

Maybe we can move this content to ththe bottom or expose it elsewhere?

**Comment by andreimoment** [comment]
![img_9477](https://cloud.githubusercontent.com/assets/6190/25679028/bde0b466-3000-11e7-9867-75c76ce93836.PNG)

**Comment by mitramartin** [comment]
sure! i'm open, want to try a different solution?

--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>

**Comment by andreimoment** [comment]
Yes, I'll propose one later today.

**Comment by andreimoment** [comment]
Take a look: https://github.com/andreimoment/tangomanual/blob/master/v1/index.md

**Comment by mitramartin** [comment]
works for me - thanks!

--
Mitra Martin | (310) 854-2466 | LinkedIn
<https://www.linkedin.com/in/mitramartin/> | Website
<http://www.mitramartin.com/> | Oxygen Tango <http://www.oxygentango.com/>

**Comment by andreimoment** [comment]
Replaced square brackets with parentheses, the brackets were breaking the links

1f969494a4cc28046c50ec4485973a8c06c83d61

**Comment by andreimoment** [comment]
Closing the TOC page issue.
