### ISSUE TITLE
Videos in 3

### ISSUE THREAD

**Issue by terrytango** [andreimoment/tangomanual#64]
The videos in 3 (3a, 3b, etc) don't seem to correspond to their respective mission. I think they're off by one.

**Comment by andreimoment** [comment]
@mitramartin, I verified that 3-A is actually a turning Ochos video and that 3-B is the box step video...

**Comment by andreimoment** [comment]
@mitramartin I'm in the process of renaming the videos on youtube and correcting them in section 3

**Comment by andreimoment** [comment]
Renamed the section 3 video and updated them in the missions. 

@terrytango, @mitramartin  could you take a look and let me know if you still see a mismatch?

**Comment by terrytango** [comment]
I think those are good now - other thing I see now is that 3-E and 3-F are
the video.

**Comment by andreimoment** [comment]
@terrytango thanks for catching this!

Updated the video in 3-F: http://tangomanual.com/v1/3-f/

Closing this issue.
